"""Increase patient location to 32

Revision ID: 192fe90d6f8d
Revises: 
Create Date: 2020-10-20 14:41:11.719822

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '192fe90d6f8d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('lis_patient', 'location',
               existing_type=sa.VARCHAR(length=12),
               type_=sa.String(length=32),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('lis_patient', 'location',
               existing_type=sa.String(length=32),
               type_=sa.VARCHAR(length=12),
               existing_nullable=True)
    # ### end Alembic commands ###
